### PR TITLE
Fixes For #23 and #22

### PR DESCRIPTION
**Pull request by OcelotWalrus**
Fixes For #23 and #22.

You actually had nothing to change, just the directory input at line 55.

### CODE REVIEW

**Review by lumbar527 — CHANGES_REQUESTED** [review]
The code still needs to be changed for if you add new enemies

I'll get to you about the other change soon

**Comment by OcelotWalrus** [comment]
> The code still needs to be changed for if you add new enemies

I already did that. There is now a `lists.yaml` where all enemies lists type are stored.

**Comment by lumbar527** [comment]
Screen Shot 2023-08-19 at 6 55 47 AM

Works

**Comment by OcelotWalrus** [comment]
enemies lists also works.

**Review by lumbar527 — APPROVED** [review]

**Comment by OcelotWalrus** [comment]
You can merge.

By the way, I would like if possible that you won't commit anything since now until my next PR. I want to do a whole re-work of the UI. And it will be annoying if you commit because there will be lots of conflicts.

**Comment by lumbar527** [comment]
What sort of rework?

**Comment by lumbar527** [comment]
Sounds cool!

**Comment by OcelotWalrus** [comment]
Thanks! So is it okay for you to not commit for now?

**Comment by lumbar527** [comment]
I'll be doing stuff on different branches.

**Comment by OcelotWalrus** [comment]
Thanks!

**Comment by OcelotWalrus** [comment]
So you can close the issues now.

**Comment by OcelotWalrus** [comment]
Small Exmaple:
image

**Comment by lumbar527** [comment]
Wow...I'm not sure about red, though.

**Comment by OcelotWalrus** [comment]
What color then? I just put red because there's flames.

**Comment by lumbar527** [comment]
Maybe grey?

**Comment by OcelotWalrus** [comment]
I'll try and send you the result.

**Comment by lumbar527** [comment]
Maybe...what if we had an options thing where you chose the theme?

**Comment by OcelotWalrus** [comment]
Yes! I'll work on that too. The UI will look insane.

**Pull request merged**
