### PR TITLE
My Patch

### PR DESCRIPTION
**Pull request by OcelotWalrus**
What this PR contains:
  * Add the ability to delete saves:
    * image
  * Some re-work on the 'UI':
    * image
  * Adds more than just the description of the item in the `'I'` view:
    * image

### CODE REVIEW

**Comment by OcelotWalrus** [comment]
I'm currently working on making the `I` command show the actual stats.

**Comment by OcelotWalrus** [comment]
> I'm currently working on making the `I` command show the actual stats.

I'm done with that.

**Review by lumbar527 — APPROVED** [review]

**Comment by OcelotWalrus** [comment]
It also adds 2 new functions to check specific player location (x or y in different variables).

**Comment by lumbar527** [comment]
OK, thanks for the help!

**Comment by OcelotWalrus** [comment]
You're welcome!

**Comment by lumbar527** [comment]
Color palettes for what? And will a GitHub continuous workflow cost GitHub Actions money?

**Comment by OcelotWalrus** [comment]
> And will a GitHub continuous workflow cost GitHub Actions money?

It's not a continuous workflow, you can make the workflow run at every push or at every x time. For the Cromha Expansion plugin, it runs at every push and it doesn't cost any money.

But since your game is just a python script, you don't need a continuous build since you don't have to build your game.

> Color palettes for what

Sorry, I didn't explain well.

I mean making color preset for making the text colored following the type of text etc...

**Comment by lumbar527** [comment]
For the colors, sure!

I think I'm fine without a build.

**Comment by OcelotWalrus** [comment]
> I think I'm fine without a build.

Yes i think too.

> For the colors, sure!

I'll make a PR about that ASAP.

**Comment by lumbar527** [comment]
Thanks!

**Pull request merged**
